spring:
  config:
    import: file:src/main/resources/custom-config.yml

app:
  sbip:
    ct:
      name: CourseTracker
      ip: 127.0.0.1
      port: 9090
      security:
        enabled: true
        token: aaskdksjdfk23942
        roles:
          - USER
          - ADMI
#logging:
#  pattern:
#    console:%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){red} %clr(${PID:- }){red}%magenta([%thread]) %highlight([%-5level]) %clr(%-40.40logger{39}){cyan} %msg%n
#loggging:
#  file:
#    path: ./logger/logs
# FAIL? ?? PATH? ????(?? ?? ???) ??, IGNORE? ?? PATH ????(?? ?? ???) ?? ???? ??