management:
  endpoints:
    web:
      exposure:
        include: ["*", "prometheus"]
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:sbipdb
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  ldap:
    embedded:
      port: 8389
      ldif: classpath:users.ldif
      base-dn: "dc=manning,dc=com"




#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#  data:
#    mongodb:
#      url: mongodb://localhost:27017/testdb

# spring
#  datasource:
#    type: org.apache.tomcat.jdbc.pool.DataSource

#logging:
#  pattern:
#    console:%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){red} %clr(${PID:- }){red}%magenta([%thread]) %highlight([%-5level]) %clr(%-40.40logger{39}){cyan} %msg%n
#loggging:
#  file:
#    path: ./logger/logs

info:
  app:
    name: Spring Boot Actuator Info Application
    description: Spring Boot Application that explores the /info endpoint
    version: 1.0.0
  build:
    artifact: ${project.artifactId}
    name: ${project.name:default}
    description: ${project.description:default}
    version: ${project.version:default}
    properties:
      java:
        version: ${java.version}



logging:
  level:
    org:
      springframework:
        web: debug
      webjars: debug
