spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-name: naver
#            client-id: lInvrg1suGNqFwAbBMBR
#            client-secret: vKBY3GO7Yt
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name, email
#          google:
#            client-name: google
#            client-id: 15683748038-co2cuhlfdt91mis4na6pvmlfi6gc9fbq.apps.googleusercontent.com
#            client-secret: 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
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            authorization-grant-type: authorization_code
#            scope: profile, email
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response